name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      endpoint: NHSDigital

  pipelines:
  - pipeline: build_pipeline
    source: "MESH-Api-Specification-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    spec_file: ${{ variables.spec_file }}
    enable_monitoring: false
    apigee_deployments:
      - environment: internal-dev
        make_spec_visible: true
        post_deploy:
              parameters:
                  service_name: ${{ variables.service_name }}
      - environment: int
        make_spec_visible: true
        post_deploy:
              parameters:
                  service_name: ${{ variables.service_name }}
