name: Build

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0  # This causes all history to be fetched, which is required for calculate-version to function

      - name: Install Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654  # v5.2.0
        with:
          distribution: 'temurin'
          java-version-file: '.tool-versions'

      - name: Install Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'

      - name: Install poetry
        run: pipx install poetry==$(grep '^poetry ' .tool-versions | awk '{print $2}')

      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version-file: '.tool-versions'
          cache: 'poetry'

      - name: Install repo
        run: make install

      - name: Set SPEC_VERSION env var
        run: echo "SPEC_VERSION=$(poetry run python scripts/calculate_version.py)" >> $GITHUB_ENV

      - name: Create release (master only)
        id: create-release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda  # v3.0.0
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.SPEC_VERSION }}
          name: ${{ env.SPEC_VERSION }}
