name: Combine Dependabot PRs

on:
  workflow_dispatch: # allows you to manually trigger the workflow
    inputs:
        ci_required:
          type: choice
          description: Require a successful build before branches are included
          options:
            - 'YES'
            - 'NO'
          required: false
          default: 'YES'

# The minimum permissions required to run this Action
permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v5.0.0
        with:
          ci_required: ${{ inputs.ci_required == 'YES' }}
          labels: dependencies
          pr_title: MESH-2092 Combined Dependabot PRs
          combine_branch_name: mesh-2092-dependabot-combined
          pr_body_header: Combined Dependabot PRs